### ISSUE TITLE
学长求一份实验报告

### ISSUE THREAD

**Issue by bestruirui** [recallfuture/CPU-Electron#11]

**Comment by recallfuture** [comment]
早没了啊，话说这么多年还在用这个课题么

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: BESTRUI ***@***.***>
发送时间: Thursday, June 22, 2023 5:58:20 PM
收件人: recallfuture/CPU-Electron ***@***.***>
抄送: Subscribed ***@***.***>
主题: [recallfuture/CPU-Electron] 学长求一份实验报告 (Issue #11)


―

**Comment by bestruirui** [comment]
是啊，要求一模一样，老师太偷懒了

**Comment by bestruirui** [comment]
谢谢学长
